repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    - id: flake8
    - id: debug-statements
    - id: check-added-large-files
    - id: check-symlinks
    - id: check-yaml
